version: '2.2'
services:
  openwrt:
    build: ./
    image: dylanpowers/openwrt:15.05.1
    restart: always
    network_mode: host
    cap_add:
      - NET_ADMIN
    volumes:
      - openwrt-config:/etc

volumes:
  openwrt-config:
